routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

setlocale(LC_ALL, 'IND');

Route::get('/', function () { 
    return redirect()->route('auth.login');
});

//Data Chart
Route::get('/u', 'AdminController@chart')->name('chart');

// Route Auth Section
Route::prefix('auth')->name('auth.')->group(function () {
    Route::get('login', 'AuthController@login')->name('login')->middleware('guest');
    Route::get('register', 'AuthController@register')->name('register')->middleware('guest');

    Route::post('submit', 'AuthController@submit')->name('submit');
    Route::post('save', 'AuthController@save')->name('save');
    Route::post('logout', 'AuthController@logout')->name('logout');
});

// Modal API
Route::prefix('modal')->middleware('auth')->name('modal.')->group(function () {
    Route::post('user/{id}', 'ApiController@user')->name('user');
    Route::post('invent/{id}', 'ApiController@invent')->name('invent');
    Route::post('borrow/{id}', 'ApiController@borrow')->name('borrow');
});

// Route Inventarisir
Route::prefix('inventaris')->name('invent.')->middleware('auth')->group(function () {
    Route::get('inventarisir', 'InventoryController@index')->name('index');
    Route::get('ruangan', 'InventoryController@room')->name('room');
    Route::get('tipe', 'InventoryController@type')->name('type');

    Route::get('tambah-barang', 'InventoryController@create_invent')->name('create_invent');
    Route::get('tambah-ruangan', 'InventoryController@create_room')->name('create_room')->middleware('admin');
    Route::get('tambah-tipe', 'InventoryController@create_type')->name('create_type')->middleware('admin');

    Route::get('edit-barang/{slug}', 'InventoryController@edit_invent')->name('edit_invent');
    Route::get('edit-ruangan/{id}', 'InventoryController@edit_room')->name('edit_room')->middleware('admin');
    Route::get('edit-tipe/{id}', 'InventoryController@edit_type')->name('edit_type')->middleware('admin');

    Route::post('list-barang', 'InventoryController@list_invent')->name('list_invent');
    Route::post('list-ruangan', 'InventoryController@list_room')->name('list_room');
    Route::post('list-tipe', 'InventoryController@list_type')->name('list_type');
    
    Route::post('simpan-barang', 'InventoryController@store_invent')->name('store_invent');
    Route::post('simpan-ruangan', 'InventoryController@store_room')->name('store_room')->middleware('admin');
    Route::post('simpan-tipe', 'InventoryController@store_type')->name('store_type')->middleware('admin');

    Route::post('update-barang/{id}', 'InventoryController@update_invent')->name('update_invent');
    Route::post('update-ruangan/{id}', 'InventoryController@update_room')->name('update_room')->middleware('admin');
    Route::post('update-tipe/{id}', 'InventoryController@update_type')->name('update_type')->middleware('admin');

    Route::post('delete-barang/{id}', 'InventoryController@destroy_invent')->name('destroy_invent');
    Route::post('delete-ruangan/{id}', 'InventoryController@destroy_room')->name('destroy_room')->middleware('admin');
    Route::post('delete-tipe/{id}', 'InventoryController@destroy_type')->name('destroy_type')->middleware('admin');

    Route::post('api/{room}', 'InventoryController@api_type')->name('api.type');

    Route::get('label/{code}', 'InventoryController@label')->name('label');
    Route::get('report', 'InventoryController@report')->name('report')->middleware('admin');
});

// Route Peminjaman
Route::prefix('peminjaman')->name('borrow.')->middleware('auth')->group(function () {
    Route::get('/daftar', 'BorrowController@index')->name('index');
    Route::get('/permintaan', 'BorrowController@request')->name('request');
    Route::get('/tambah', 'BorrowController@create')->name('create');
    Route::get('/edit/{id}', 'BorrowController@edit')->name('edit');
    
    Route::post('api/{code}', 'BorrowController@api')->name('api');
    Route::post('list', 'BorrowController@list')->name('list');
    Route::post('list_request', 'BorrowController@list_request')->name('list_request');
    Route::post('store', 'BorrowController@store')->name('store');
    Route::post('update/{id}', 'BorrowController@update')->name('update');
    Route::get('update-status/{id}/{param}', 'BorrowController@update_request')->name('update_request');
});

// Route Admin
Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('backup', 'AdminController@backup')->name('backup');

    Route::get('/profile','ProfileController@profile')->name('profile');
    Route::post('/update', 'ProfileController@update')->name('update');

    Route::prefix('pengguna')->name('user.')->group(function () {
        Route::get('/daftar', 'UserController@index')->name('index');
        Route::get('/permintaan', 'UserController@request')->name('request');
        Route::get('/tambah', 'UserController@create')->name('create');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');

        Route::post('list', 'UserController@list')->name('list');
        Route::post('list_request', 'UserController@list_request')->name('list_request');
        Route::post('store', 'UserController@store')->name('store');
        Route::post('update/{id}', 'UserController@update')->name('update');
        Route::get('update_request/{id}', 'UserController@update_request')->name('update_request');
        Route::post('destroy/{id}', 'UserController@destroy')->name('destroy');
    });

    Route::get('/log', function () {
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route Operator
Route::prefix('operator')->name('operator.')->middleware('operator')->group(function () {
    Route::get('/', 'OperatorController@index')->name('index');

    Route::get('/profile','ProfileController@profile')->name('profile');
    Route::post('/update', 'ProfileController@update')->name('update');

    Route::get('/log', function () {
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route Peminjaman
// Route::prefix('peminjam')->name('peminjam.')->middleware('borrower')->group(function() {
Route::prefix('peminjam')->name('peminjam.')->group(function() {
    Route::get('/', function() {
        return view('peminjam/index');
    })->name('index');

    Route::get('/profile', function() {
        return view('profile');
    })->name('profile');

    Route::get('/keranjang', function() {
        return view('peminjam/keranjang');
    })->name('keranjang');

    Route::prefix('peminjaman')->name('borrow.')->group(function () {
        Route::get('daftar', function () {
            return view('peminjam/list-peminjaman');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-peminjaman');
        })->name('detail');
    });

    Route::prefix('inventaris')->name('invent.')->group(function () {
        Route::get('/', function () {
            return view('peminjam/inventaris');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-barang');
        })->name('detail');
    });
});

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\RoomType;
use App\Http\Requests\Inventory;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;

use App\Room;
use App\Type;
use App\Inventory as Inventories;
use App\User;
use App\BorrowDetail;
use App\Borrow;

use Validator;

use CodeItNow\BarcodeBundle\Utils\BarcodeGenerator;

class InventoryController extends Controller
{
    /**
     * untuk menampilkan halaman list data barang
     *
     * @return void
     */
    public function index()
    {
        return view('inventory/index');
    }

    /**
     * untuk menampilkan halaman list data ruangan
     *
     * @return void
     */
    public function room()
    {
        return view('inventory/room');
    }

    /**
     * untuk menampilkan halaman list data tipe barang
     *
     * @return void
     */
    public function type()
    {
        return view('inventory/type');
    }

    /**
     * untuk mengambil list data barang
     *
     * @return void
     */
    public function list_invent()
    {
        $invent = Inventories::all();

        $data = array();
        foreach($invent as $item) {
            $room = Room::findOrFail($item->room_id);

            $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
            $act.= '<i class="fa fa-ellipsis-h"></i>';
            $act.= '</a>';
            $act.= '<div class="dropdown-menu" style="width:50px;">';
            $act.= '<a class="dropdown-item" href="javascript:void(0)" onclick="showData('.$item->id.')">Detail</a>';
            $act.= '<a class="dropdown-item" href="javascript:void(0)" onclick="printLabel(\''.$item->code.'\')">Print Label</a>';
            $act.= '<a class="dropdown-item" href="'.route("invent.edit_invent", $item->id).'">Edit</a>';
            $act.= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData('.$item->id.')">Delete</a>';
            $act.= '</div>';
            $item['action'] = $act;
            $item['picture'] = '<img src="'.asset($item->picture).'" class="img-thumb">';
            $item['room_id'] = $room->name;
            
            if($item->condition == "Baik") {
                $item['condition'] = '<span class="badge badge-pill badge-primary">'.$item->condition.'</span>';
            } else {
                $item['condition'] = '<span class="badge badge-pill badge-danger">'.$item->condition.'</span>';
            }

            $data[] = $item;
        }
        echo json_encode(array("sEcho" => 1, "aaData" => $data));
    }

    /**
     * mengambil/mengolah list data ruangan untuk ditampilkan ke table list ruangan
     *
     * @return void
     */
    public function list_room()
    {
        $room = Room::all();

        $data = array();
        foreach($room as $item) {
            $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
            $act .= '<i class="fa fa-ellipsis-h"></i>';
            $act .= '</a>';
            $act .= '<div class="dropdown-menu" style="width:50px;">';
            if(Auth::user()->level_id === 3) {
                $act .= '<a class="dropdown-item" href="'.route("invent.edit_room", $item->id).'">Edit</a>';
                $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData('.$item->id.')">Delete</a>';
            }
            $act .= '</div>';
            $item['action'] = $act;
            $data[] = $item;
        }

        echo json_encode(array("sEcho" => 1, "aaData" => $data));
    }

    /**
     * mengambil/mengolah list data ruangan untuk ditampilkan ke table list ruangan
     *
     * @return void
     */
    public function list_type()
    {
        $type = Type::all();

        $data = array();
        foreach($type as $item) {
            $act = '<a href="#" class="non-caret dropdown-toggle" data-toggle="dropdown">';
            $act .= '<i class="fa fa-ellipsis-h"></i>';
            $act .= '</a>';
            $act .= '<div class="dropdown-menu" style="width:50px;">';
            if(Auth::user()->level_id === 3) {
                $act .= '<a class="dropdown-item" href="'.route("invent.edit_type", $item->id).'">Edit</a>';
                $act .= '<a class="dropdown-item" href="javascript:void(0)" onclick="deleteData('.$item->id.')">Delete</a>';
            }
            $act .= '</div>';
            $item['action'] = $act;
            $data[] = $item;
        }

        echo json_encode(array("sEcho" => 1, "aaData" => $data));
    }

    /**
     * Menampilkan halaman create barang
     *
     * @return void
     */
    public function create_invent()
    {
        $room = Room::all();
        $type = Type::all();

        return view('inventory/create__invent', compact('room', 'type'));
    }

    /**
     * Menampilkan halaman create ruangan
     *
     * @return void
     */
    public function create_room()
    {
        return view('inventory/create__room');
    }

    /**
     * Menampilkan halaman create tipe barang
     *
     * @return void
     */
    public function create_type()
    {
        return view('inventory/create__type');
    }

    /**
     * Menampilkan halaman edit barang
     *
     * @param [type] $slug
     * @return void
     */
    public function edit_invent($slug)
    {
        $data = Inventories::findOrFail($slug);
        $room = Room::all();
        $type = Type::all();
        
        return view('inventory/create__invent', compact('data', 'room', 'type'));
    }

    /**
     * Menampilkan halaman edit ruangan
     *
     * @param [type] $code
     * @return void
     */
    public function edit_room($code)
    {
        $data = Room::findOrFail($code);
        return view('inventory/create__room', compact('data'));
    }

    /**
     * Menampilkan halaman edit tipe barang
     *
     * @param [type] $code
     * @return void
     */
    public function edit_type($code)
    {
        $data = Type::findOrFail($code);
        return view('inventory/create__type', compact('data'));
    }

    /**
     * Untuk men-save data barang ke database
     *
     * @param Inventory $request
     * @return void
     */
    public function store_invent(Inventory $request)
    {
        //slug
        $str = str_slug($request->name);

        //image process
        $img = $request->file('picture');
        $imgName = $str.'.'.$img->getClientOriginalExtension();
        $path = public_path('img\inventory/');
        $request->file('picture')->move($path, $imgName);

        Inventories::create([
            'user_id' => Auth::user()->id,
            'type_id' => $request->type_id,
            'room_id' => $request->room_id,
            'code' => $request->code,
            'name' => $request->name,
            'condition' => $request->condition,
            'desc' => $request->desc,
            'qty' => $request->qty,
            'picture' => 'img/inventory/'.$imgName
        ]);

        activity()
            ->withProperties([
                'obj' => $request->name.' pada '.date('H:i'),
                'by' => '<b>'.session('name').'</b>'
            ])
            ->log('telah membuat barang baru yaitu : ');

        return redirect()->route('invent.create_invent')->with([
            'success' => 'Selamat! Anda berhasil menambahkan barang baru!',
            'status' => TRUE
        ]);
    }

    /**
     * Untuk men-save data ruangan ke database
     *
     * @param Request $request
     * @return void
     */
    public function store_room(Request $request)
    {   
        $request->validate([
            'code' => 'required|unique:rooms|alpha_num',
            'name' => 'required',
            'desc' => 'required'
        ], [
            'code.alpha_num' => 'Kode harus diisi dengan valid',
            'code.required' => 'Kode harus diisi',
            'code.unique' => 'Kode sudah digunakan',
            'name.required' => 'Nama harus diisi',
            'desc.required' => 'Deskripsi harus diisi'
        ]);

        Room::create($request->all());

        activity()
            ->withProperties([
                'obj' => $request->name.' dengan kode '.$request->code,
                'by' => '<b>'.Auth::user()->admin->name.'</b>'
            ])
            ->log('telah membuat ruangan baru yaitu :');

        return redirect()->route('invent.create_room')->with([
            'success' => 'Selamat! Anda berhasil memasukkan ruangan baru!',
            'status' => TRUE
        ]);
    }

    /**
     * Untuk men-save data tipe barang ke database
     *
     * @param Request $request
     * @return void
     */
    public function store_type(Request $request)
    {   
        $request->validate([
            'code' => 'required|unique:types|alpha_num',
            'name' => 'required',
            'desc' => 'required'
        ], [
            'code.alpha_num' => 'Kode harus diisi dengan valid',
            'code.required' => 'Kode harus diisi',
            'code.unique' => 'Kode sudah digunakan',
            'name.required' => 'Nama harus diisi',
            'desc.required' => 'Deskripsi harus diisi'
        ]);

        Type::create($request->all());

        activity()
            ->withProperties([
                'obj' => $request->name.' dengan kode '.$request->code,
                'by' => '<b>'.Auth::user()->admin->name.'</b>'
            ])
            ->log('telah membuat tipe barang baru yaitu :');

            return redirect()->route('invent.create_type')->with([
            'success' => 'Selamat! Anda berhasil memasukkan tipe baru!',
            'status' => TRUE
        ]);
    }

    /**
     * Untuk mengupdate data barang
     *
     * @param Request $request
     * @param [type] $id
     * @return void
     */
    public function update_invent(Request $request, $id) 
    {
        $request->validate([
            'picture' => 'image|max:10000',

resources/views/inventory/create__invent.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-3">
        <div class="col-lg-12">

            <div class="card card-base">
                <h6 class="card-header">Form {{ @$data ? "Edit" : "Tambah" }} Barang</h6>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">
                            @if (@$data)
                                <form action="{{ route('invent.update_invent', @$data->id) }}" method="post" enctype="multipart/form-data">
                            @else
                                <form action="{{ route('invent.store_invent') }}" method="post" enctype="multipart/form-data">
                            @endif
                                @csrf
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="choose-photo bg-light {{ $errors->has('picture') ? 'has-error' : '' }}">
                                            <img src="{{ @$data->picture ? asset(@$data->picture) : '' }}" class="img-fluid is-invalid" id="img-file">
                                        </div>
                                        <span class="text-danger">
                                            {{ $errors->has('picture') ? 'Format file tidak didukung' : '' }}
                                        </span>
                                    </div>

                                    <div class="col-md-9">
                                        <input type="file" name="picture" class="img-preview d-none">
                                        <div class="row">
                                            <div class="col-md-7">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Nama barang</label>
                                                    <input type="text" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" value="{{ old('name', @$data->name) }}">
                                                    <span class="invalid-feedback">
                                                        {{ $errors->first('name') }}
                                                    </span>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Tipe barang</label>
                                                    <select name="type_id" id="type" class="form-control" {{ @$data ? 'disabled' : '' }}>

                                                        @foreach ($type as $item)
                                                            <option value="{{ $item->id }}" {{ @$data->type_id === $item->id ? 'selected' : '' }}>{{ $item->name }}</option>
                                                        @endforeach

                                                    </select>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Kode barang</label>
                                                    <input class="form-control disabled {{ $errors->has('code') ? 'is-invalid' : '' }}" type="text" name="code" value="{{ old('code', @$data->code) }}" readonly>
                                                    <span class="invalid-feedback">
                                                        {{ $errors->first('code') }}
                                                    </span>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Ruangan</label>
                                                    <select name="room_id" id="room" class="form-control">
                                                        
                                                        @foreach ($room as $rooms)
                                                            <option value="{{ $rooms->id }}" {{ @$data->room_id === $rooms->id ? 'selected' : '' }}>{{ $rooms->name }}</option>
                                                        @endforeach

                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Kondisi barang</label>
                                                    <select name="condition" id="" class="form-control">
                                                        <option value="Baik" {{ @$data->condition == "Baik" ? 'selected' : '' }}>Baik</option>
                                                        <option value="Rusak" {{ @$data->condition == "Rusak" ? 'selected' : '' }}>Rusak</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-2">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Stok</label>
                                                    <input type="number" name="qty" class="form-control {{ $errors->has('qty') ? 'is-invalid' : '' }}" value="{{ old('qty', @$data->qty) }}">
                                                    <span class="invalid-feedback">
                                                        {{ $errors->first('qty') }}
                                                    </span>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="text-base text-bold">Deskripsi</label>
                                                    <textarea name="desc" class="form-control {{ $errors->has('desc') ? 'is-invalid' : '' }}" rows="4">{{ old('desc', @$data->desc) }}</textarea>       
                                                    <span class="invalid-feedback">
                                                        {{ $errors->first('desc') }}
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>                  

                                </div>
                                <div class="row mt-3">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('invent.index') }}" class="btn btn-secondary btn-rounded">Cancel</a>
                                        &nbsp;
                                        <input type="submit" class="btn btn-base btn-rounded">
                                    </div>
                                </div>                
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

@section('script')
    <script>
        $(function() {
            var code = $('#type').val();

            if({{ @$data ? 0 : 1 }}) {
                axios.post("{{ url('inventaris/api') }}/" + code)
                .then((res) => {
                    console.log(res.data);
                    var result = res.data;
                    $('[name="code"]').val(result.code);
                }).catch((err) => {
                    console.log(err);
                })
            }

            $('#type').change(() => {
                code = $('#type').val();
                
                axios.post("{{ url('inventaris/api') }}/" + code)
                .then((res) => {
                    console.log(res.data);
                    var result = res.data;
                    $('[name="code"]').val(result.code);
                }).catch((err) => {
                    console.log(err);
                })
            })

            if({{ session('status') ?? '0' }}) {
                swal({
                    title: "Selamat!",
                    text: "{{ session('success') }}",
                    icon: "success",
                    buttons: true,
                }).then((willRedirect) => {
                    if(willRedirect) {
                        window.location = '{{ route("invent.index") }}'
                    }
                })                   
            }
        })
    </script>
@endsection

resources/views/inventory/create__room.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-3">
        <div class="col-lg-12">

            <div class="card card-base">
                <h6 class="card-header">Form {{ @$data ? "Edit" : "Tambah" }} Ruangan</h6>
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12">
                            @if (@$data)
                                <form action="{{ route('invent.update_room', @$data->id) }}" method="post" id="form">
                            @else
                                <form action="{{ route('invent.store_room') }}" method="post" id="form">
                            @endif
                                @csrf
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Kode</label>
                                            <input type="text" name="code" class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" value="{{ old('code', @$data->code) }}" {{ @$data ? 'disabled' : '' }}>
                                            <span class="invalid-feedback">
                                                {{ $errors->first('code') }}
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Nama</label>
                                            <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" value="{{ old('name', @$data->name) }}">
                                            <span class="invalid-feedback">
                                                {{ $errors->first('name') }}
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="text-base text-bold">Deskripsi</label>
                                            <textarea name="desc" rows="4" class="form-control {{ $errors->has('desc') ? 'is-invalid' : ''}}">{{ old('desc', @$data->desc) }}</textarea>
                                            <span class="invalid-feedback">
                                                {{ $errors->first('desc') }}
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('invent.room') }}" class="btn btn-secondary btn-rounded">Cancel</a>
                                        &nbsp;
                                        <input type="submit" class="btn btn-base btn-rounded">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

@section('script')
    <script>
        $(function() {
            if({{ session('status') ?? '0' }}) {
                swal({
                    title: "Selamat!",
                    text: "{{ session('success') }}",
                    icon: "success",
                    buttons: true,
                }).then((willRedirect) => {
                    if(willRedirect) {
                        window.location = '{{ route("invent.room") }}'
                    }
                })                
            }
        })
    </script>
@endsection