routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

setlocale(LC_ALL, 'IND');

Route::get('/', function () { 
    return redirect()->route('auth.login');
});

//Data Chart
Route::get('/u', 'AdminController@chart')->name('chart');

// Route Auth Section
Route::prefix('auth')->name('auth.')->group(function () {
    Route::get('login', 'AuthController@login')->name('login')->middleware('guest');
    Route::get('register', 'AuthController@register')->name('register')->middleware('guest');

    Route::post('submit', 'AuthController@submit')->name('submit');
    Route::post('save', 'AuthController@save')->name('save');
    Route::post('logout', 'AuthController@logout')->name('logout');
});

// Modal API
Route::prefix('modal')->middleware('auth')->name('modal.')->group(function () {
    Route::post('user/{id}', 'ApiController@user')->name('user');
    Route::post('invent/{id}', 'ApiController@invent')->name('invent');
    Route::post('borrow/{id}', 'ApiController@borrow')->name('borrow');
});

// Route Inventarisir
Route::prefix('inventaris')->name('invent.')->middleware('auth')->group(function () {
    Route::get('inventarisir', 'InventoryController@index')->name('index');
    Route::get('ruangan', 'InventoryController@room')->name('room');
    Route::get('tipe', 'InventoryController@type')->name('type');

    Route::get('tambah-barang', 'InventoryController@create_invent')->name('create_invent');
    Route::get('tambah-ruangan', 'InventoryController@create_room')->name('create_room')->middleware('admin');
    Route::get('tambah-tipe', 'InventoryController@create_type')->name('create_type')->middleware('admin');

    Route::get('edit-barang/{slug}', 'InventoryController@edit_invent')->name('edit_invent');
    Route::get('edit-ruangan/{id}', 'InventoryController@edit_room')->name('edit_room')->middleware('admin');
    Route::get('edit-tipe/{id}', 'InventoryController@edit_type')->name('edit_type')->middleware('admin');

    Route::post('list-barang', 'InventoryController@list_invent')->name('list_invent');
    Route::post('list-ruangan', 'InventoryController@list_room')->name('list_room');
    Route::post('list-tipe', 'InventoryController@list_type')->name('list_type');
    
    Route::post('simpan-barang', 'InventoryController@store_invent')->name('store_invent');
    Route::post('simpan-ruangan', 'InventoryController@store_room')->name('store_room')->middleware('admin');
    Route::post('simpan-tipe', 'InventoryController@store_type')->name('store_type')->middleware('admin');

    Route::post('update-barang/{id}', 'InventoryController@update_invent')->name('update_invent');
    Route::post('update-ruangan/{id}', 'InventoryController@update_room')->name('update_room')->middleware('admin');
    Route::post('update-tipe/{id}', 'InventoryController@update_type')->name('update_type')->middleware('admin');

    Route::post('delete-barang/{id}', 'InventoryController@destroy_invent')->name('destroy_invent');
    Route::post('delete-ruangan/{id}', 'InventoryController@destroy_room')->name('destroy_room')->middleware('admin');
    Route::post('delete-tipe/{id}', 'InventoryController@destroy_type')->name('destroy_type')->middleware('admin');

    Route::post('api/{room}', 'InventoryController@api_type')->name('api.type');

    Route::get('label/{code}', 'InventoryController@label')->name('label');
    Route::get('report', 'InventoryController@report')->name('report')->middleware('admin');
});

// Route Peminjaman
Route::prefix('peminjaman')->name('borrow.')->middleware('auth')->group(function () {
    Route::get('/daftar', 'BorrowController@index')->name('index');
    Route::get('/permintaan', 'BorrowController@request')->name('request');
    Route::get('/tambah', 'BorrowController@create')->name('create');
    Route::get('/edit/{id}', 'BorrowController@edit')->name('edit');
    
    Route::post('api/{code}', 'BorrowController@api')->name('api');
    Route::post('list', 'BorrowController@list')->name('list');
    Route::post('list_request', 'BorrowController@list_request')->name('list_request');
    Route::post('store', 'BorrowController@store')->name('store');
    Route::post('update/{id}', 'BorrowController@update')->name('update');
    Route::get('update-status/{id}/{param}', 'BorrowController@update_request')->name('update_request');
});

// Route Admin
Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('backup', 'AdminController@backup')->name('backup');

    Route::get('/profile','ProfileController@profile')->name('profile');
    Route::post('/update', 'ProfileController@update')->name('update');

    Route::prefix('pengguna')->name('user.')->group(function () {
        Route::get('/daftar', 'UserController@index')->name('index');
        Route::get('/permintaan', 'UserController@request')->name('request');
        Route::get('/tambah', 'UserController@create')->name('create');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');

        Route::post('list', 'UserController@list')->name('list');
        Route::post('list_request', 'UserController@list_request')->name('list_request');
        Route::post('store', 'UserController@store')->name('store');
        Route::post('update/{id}', 'UserController@update')->name('update');
        Route::get('update_request/{id}', 'UserController@update_request')->name('update_request');
        Route::post('destroy/{id}', 'UserController@destroy')->name('destroy');
    });

    Route::get('/log', function () {
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route Operator
Route::prefix('operator')->name('operator.')->middleware('operator')->group(function () {
    Route::get('/', 'OperatorController@index')->name('index');

    Route::get('/profile','ProfileController@profile')->name('profile');
    Route::post('/update', 'ProfileController@update')->name('update');

    Route::get('/log', function () {
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route Peminjaman
// Route::prefix('peminjam')->name('peminjam.')->middleware('borrower')->group(function() {
Route::prefix('peminjam')->name('peminjam.')->group(function() {
    Route::get('/', function() {
        return view('peminjam/index');
    })->name('index');

    Route::get('/profile', function() {
        return view('profile');
    })->name('profile');

    Route::get('/keranjang', function() {
        return view('peminjam/keranjang');
    })->name('keranjang');

    Route::prefix('peminjaman')->name('borrow.')->group(function () {
        Route::get('daftar', function () {
            return view('peminjam/list-peminjaman');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-peminjaman');
        })->name('detail');
    });

    Route::prefix('inventaris')->name('invent.')->group(function () {
        Route::get('/', function () {
            return view('peminjam/inventaris');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-barang');
        })->name('detail');
    });
});

app/Operator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\User;

class Operator extends Model
{
    protected $fillable = ['user_id', 'name', 'nip', 'ip_address'];

    /**
     * Untuk merelasikan dengan model user
     *
     * @return void
     */
    public function user ()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;

use App\Borrow;
use App\Borrower;
use App\BorrowDetail;
use App\Inventory;
use App\User;

use Carbon\Carbon;

class OperatorController extends Controller
{
    /**
     * Untuk menampilkan halaman dashboard operator
     *
     * @return void
     */
    public function index()
    {
        $data = array(
            'goods' => Inventory::all()->count(),
            'borrow' => BorrowDetail::where('status', 'Dipinjam')->count(),
            'borrower' => Borrower::all()->count(),
            'request' => BorrowDetail::where('status', 'Pending')->count()
        );

        $user = DB::table('new_users')->get();
        $newUser = array();

        foreach($user as $users) {
            $newUser[] = $users;
        }

        $good = DB::table('inventories')
                ->orderBy('created_at', 'desc')
                ->limit(5)
                ->get();
        $newGoods = array();

        foreach($good as $item) {
            $newGoods[] = $item;
        }

        return view('operator/index', compact('data', 'newUser', 'newGoods'));
    }

    /**
     * Untuk mengolah data peminjaman dan ditampilkan dalam chart
     *
     * @return void
     */
    public function chart()
    {
        $data = Borrow::get(['id', 'borrow_at'])
                ->groupBy(function ($d) {
                    return Carbon:: parse($d -> borrow_at) -> format('m');
                });
        $collection = array();
        $setData = array();

        $nol = "0";
        for ($i = 1; $i <= 12; $i++) {
            if ($i > 9) {
                $nol = "";
            }

            if (!@$data[$nol.$i]) {
                $collection[$i] = array();
            } else {
                $collection[$i] = $data[$nol.$i];
            }
        }

        foreach($collection as $item) {
            $setData[] = count($item);
        }

        return $setData;
    }
}

resources/views/operator/_sidebar.blade.php
<div class="col-lg-2 sidebar pr-0">
    <ul class="nav flex-column">
        <li class="menu-header">Dashboard</li>
        <li class="nav-item" id="beranda">
            <a href="{{ route('operator.index') }}" class="nav-link">
                <i class="fa fa-tachometer"></i>
                Dashboard
            </a>
        </li>
        <li class="menu-header">Modul</li>
        <li class="nav-item has-submenu" id="inventaris">
            <a href="javascript:void()" class="nav-link">
                <i class="fa fa-dropbox"></i>
                Inventaris
                <i class="fa {{ Request::segment(2) == "inventaris" ? "fa-minus" : "fa-plus" }} ml-2 icon-add"></i>
            </a>
            <ul class="submenu list-unstyled" style="display: {{ Request::segment(2) == 'inventaris' ? "block" : "none"}}">
                <li class="nav-item">
                    <a href="{{ route('invent.index') }}" class="inventarisir">Inventarisir</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('invent.room') }}" class="ruangan">Ruangan</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('invent.type') }}" class="tipe">Tipe Barang</a>
                </li>
            </ul>
        </li>
        <li class="nav-item has-submenu" id="peminjaman">
            <a href="javascript:void()" class="nav-link">
                <i class="fa fa-clipboard"></i>
                Peminjaman
                <i class="fa {{ Request::segment(2) == "peminjaman" ? "fa-minus" : "fa-plus" }} ml-2 icon-add"></i>
            </a>
            <ul class="submenu list-unstyled" style="display: {{ Request::segment(2) == 'peminjaman' ? "block" : "none"}}">
                <li class="nav-item">
                    <a href="{{ route('borrow.index') }}" class="daftar">Daftar Peminjaman</a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('borrow.request') }}" class="permintaan">Permintaan Peminjaman</a>
                </li>
            </ul>
        </li>
        <li class="nav-item" id="log">
            <a href="{{ route('operator.log') }}" class="nav-link">
                <i class="fa fa-share-alt"></i>
                Log Aktifitas
            </a>
        </li>
    </ul>
</div

resources/views/operator/index.blade.php
@extends('template')

@section('content')
    
    <div class="row mt-5">
        {{-- Item --}}
        <div class="col-lg-4">
            <div class="row">
                
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="fa fa-tachometer card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Barang</p>
                            <p class="text-semibold card-icon__number">{{ @$data['goods'] }}</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="ni ni-credit-card card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Peminjaman</p>
                            <p class="text-semibold card-icon__number">{{ @$data['borrow'] }}</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="ni ni-user-run card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Peminjam</p>
                            <p class="text-semibold card-icon__number">{{ @$data['borrower'] }}</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="ni ni-single-copy-04 card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Permintaan</p>
                            <p class="text-semibold card-icon__number">{{ @$data['request'] }}</p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        {{-- End of Item --}}

        {{-- Chart --}}
        <div class="col-lg-8 mb-0">
            <div class="card bg-gradient-default shadow">
                <div class="card-header bg-transparent">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="text-uppercase text-light ls-1 mb-1">Grafik</h6>
                            <h2 class="text-white mb-0">Peminjaman</h2>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {{-- Chart Peminjaman --}}
                    <div class="chart">
                        <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                        {{-- Chart Wrapper --}}
                        <canvas id="chart-borrow" class="chart-canvas chartjs-render-monitor" style="display: block; width: 621px; height: 187px;"></canvas>
                        {{-- End of Chart Wrapper --}}
                    </div>
                    {{-- End of Chart --}}
                </div>
            </div>
        </div>
        {{-- End of Chart --}}
    </div>

    <div class="row mt-3">
        {{-- Peminjam --}}
        <div class="col-lg-7">
            <div class="card">
                <div class="card-body">
                     
                    <h3 class="text-semibold">Peminjam Baru</h3>
                    <table id="myTable" class="table mt-3">
                        <thead class="thead-base">
                            <tr>
                                <th width="5"></th>
                                <th width="40">Nama</th>
                                <th width="10">Status</th>
                                <th width="10" class="align-center">Telepon</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($newUser as $user)    
                                <tr>
                                    <td class="align-middle">
                                        <img src="{{ asset('img/no-photo.png') }}" class="img-round img-thumb">
                                    </td>
                                    <td class="align-middle">{{ $user->name }}</td>
                                    <td class="align-middle">{{ $user->status }}</td>
                                    <td class="align-middle">{{ $user->phone }}</td>
                                </tr>
                            @endforeach

                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
        {{-- End of Peminjam --}}

        {{-- Barang --}}
        <div class="col-lg-5">
            <div class="card">
                <div class="card-body">
                        
                    <h3 class="text-semibold">Daftar Barang</h3>
                    <table id="myTable2" class="table mt-3">
                        <thead class="thead-base">
                            <tr>
                                <th width="40">Nama</th>
                                <th width="10" class="text-center">Kondisi</th>
                                <th width="10" class="text-center">Stok</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($newGoods as $item)
                                <tr>
                                    <td class="align-middle">{{ $item->name }}</td>
                                    <td class="align-middle text-center">
                                        <span class="badge badge-pill badge-success">{{ $item->condition }}</span>
                                    </td>
                                    <td class="align-middle text-center">{{ $item->qty }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                
                </div>
            </div>
        </div>
        {{-- End of Barang --}}
    </div>

@endsection

@section('script')
    <script>
        $(function () {
            var monthSetData = new Array();

            axios.get('{{ route("chart") }}')
            .then((res) => {
                monthSetData.push(res.data)
                console.log(monthSetData[0])

                // Chart
                var config = {
                    type: 'line',
                    data: {
                        labels: [
                            'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
                        ],
                        datasets: [{
                            fill: true,
                            backgroundColor: "#6777ef",
                            borderColor: "#6777ef",
                            data: monthSetData[0],
                        }]
                    },
                    options: {
                        responsive: true,
                        labels: {
                            fontColor: 'white'
                        },
                        elements: {
                            point: {
                                radius: 0
                            }
                        },
                        legend: {
                            display: false,
                        },
                        tooltips: {
                            mode: 'index',
                            intersect: false,
                        },
                        hover: {
                            mode: 'nearest',
                            intersect: true
                        },
                        scales: {
                            xAxes: [{
                                display: true,
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Bulan',
                                    fontColor: "white"
                                },
                                ticks: {
                                    fontColor: 'white'
                                }
                            }],
                            yAxes: [{
                                display: true,
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Jumlah',
                                    fontColor: "white"
                                },
                                ticks: {
                                    fontColor: 'white'
                                }
                            }]
                        }
                    }
                };

                var ctx = document.getElementById('chart-borrow').getContext('2d');
                var myLineChart = new Chart(ctx, config);
            })
            .catch((err) => {
                console.log(err)
            })
            
        })
    </script>
@endsection