routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

setlocale(LC_ALL, 'IND');

Route::get('/', function () { 
    return redirect()->route('auth.login');
});

//Data Chart
Route::get('/u', 'AdminController@chart')->name('chart');

// Route Auth Section
Route::prefix('auth')->name('auth.')->group(function () {
    Route::get('login', 'AuthController@login')->name('login')->middleware('guest');
    Route::get('register', 'AuthController@register')->name('register')->middleware('guest');

    Route::post('submit', 'AuthController@submit')->name('submit');
    Route::post('save', 'AuthController@save')->name('save');
    Route::post('logout', 'AuthController@logout')->name('logout');
});

// Modal API
Route::prefix('modal')->middleware('auth')->name('modal.')->group(function () {
    Route::post('user/{id}', 'ApiController@user')->name('user');
    Route::post('invent/{id}', 'ApiController@invent')->name('invent');
    Route::post('borrow/{id}', 'ApiController@borrow')->name('borrow');
});

// Route Inventarisir
Route::prefix('inventaris')->name('invent.')->middleware('auth')->group(function () {
    Route::get('inventarisir', 'InventoryController@index')->name('index');
    Route::get('ruangan', 'InventoryController@room')->name('room');
    Route::get('tipe', 'InventoryController@type')->name('type');

    Route::get('tambah-barang', 'InventoryController@create_invent')->name('create_invent');
    Route::get('tambah-ruangan', 'InventoryController@create_room')->name('create_room')->middleware('admin');
    Route::get('tambah-tipe', 'InventoryController@create_type')->name('create_type')->middleware('admin');

    Route::get('edit-barang/{slug}', 'InventoryController@edit_invent')->name('edit_invent');
    Route::get('edit-ruangan/{id}', 'InventoryController@edit_room')->name('edit_room')->middleware('admin');
    Route::get('edit-tipe/{id}', 'InventoryController@edit_type')->name('edit_type')->middleware('admin');

    Route::post('list-barang', 'InventoryController@list_invent')->name('list_invent');
    Route::post('list-ruangan', 'InventoryController@list_room')->name('list_room');
    Route::post('list-tipe', 'InventoryController@list_type')->name('list_type');
    
    Route::post('simpan-barang', 'InventoryController@store_invent')->name('store_invent');
    Route::post('simpan-ruangan', 'InventoryController@store_room')->name('store_room')->middleware('admin');
    Route::post('simpan-tipe', 'InventoryController@store_type')->name('store_type')->middleware('admin');

    Route::post('update-barang/{id}', 'InventoryController@update_invent')->name('update_invent');
    Route::post('update-ruangan/{id}', 'InventoryController@update_room')->name('update_room')->middleware('admin');
    Route::post('update-tipe/{id}', 'InventoryController@update_type')->name('update_type')->middleware('admin');

    Route::post('delete-barang/{id}', 'InventoryController@destroy_invent')->name('destroy_invent');
    Route::post('delete-ruangan/{id}', 'InventoryController@destroy_room')->name('destroy_room')->middleware('admin');
    Route::post('delete-tipe/{id}', 'InventoryController@destroy_type')->name('destroy_type')->middleware('admin');

    Route::post('api/{room}', 'InventoryController@api_type')->name('api.type');

    Route::get('label/{code}', 'InventoryController@label')->name('label');
    Route::get('report', 'InventoryController@report')->name('report')->middleware('admin');
});

// Route Peminjaman
Route::prefix('peminjaman')->name('borrow.')->middleware('auth')->group(function () {
    Route::get('/daftar', 'BorrowController@index')->name('index');
    Route::get('/permintaan', 'BorrowController@request')->name('request');
    Route::get('/tambah', 'BorrowController@create')->name('create');
    Route::get('/edit/{id}', 'BorrowController@edit')->name('edit');
    
    Route::post('api/{code}', 'BorrowController@api')->name('api');
    Route::post('list', 'BorrowController@list')->name('list');
    Route::post('list_request', 'BorrowController@list_request')->name('list_request');
    Route::post('store', 'BorrowController@store')->name('store');
    Route::post('update/{id}', 'BorrowController@update')->name('update');
    Route::get('update-status/{id}/{param}', 'BorrowController@update_request')->name('update_request');
});

// Route Admin
Route::prefix('admin')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');
    Route::get('backup', 'AdminController@backup')->name('backup');

    Route::get('/profile','ProfileController@profile')->name('profile');
    Route::post('/update', 'ProfileController@update')->name('update');

    Route::prefix('pengguna')->name('user.')->group(function () {
        Route::get('/daftar', 'UserController@index')->name('index');
        Route::get('/permintaan', 'UserController@request')->name('request');
        Route::get('/tambah', 'UserController@create')->name('create');
        Route::get('/edit/{id}', 'UserController@edit')->name('edit');

        Route::post('list', 'UserController@list')->name('list');
        Route::post('list_request', 'UserController@list_request')->name('list_request');
        Route::post('store', 'UserController@store')->name('store');
        Route::post('update/{id}', 'UserController@update')->name('update');
        Route::get('update_request/{id}', 'UserController@update_request')->name('update_request');
        Route::post('destroy/{id}', 'UserController@destroy')->name('destroy');
    });

    Route::get('/log', function () {
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route Operator
Route::prefix('operator')->name('operator.')->middleware('operator')->group(function () {
    Route::get('/', 'OperatorController@index')->name('index');

    Route::get('/profile','ProfileController@profile')->name('profile');
    Route::post('/update', 'ProfileController@update')->name('update');

    Route::get('/log', function () {
        $act = Activity::all();

        return view('admin/activity', compact('act'));
    })->name('log');
});

// Route Peminjaman
// Route::prefix('peminjam')->name('peminjam.')->middleware('borrower')->group(function() {
Route::prefix('peminjam')->name('peminjam.')->group(function() {
    Route::get('/', function() {
        return view('peminjam/index');
    })->name('index');

    Route::get('/profile', function() {
        return view('profile');
    })->name('profile');

    Route::get('/keranjang', function() {
        return view('peminjam/keranjang');
    })->name('keranjang');

    Route::prefix('peminjaman')->name('borrow.')->group(function () {
        Route::get('daftar', function () {
            return view('peminjam/list-peminjaman');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-peminjaman');
        })->name('detail');
    });

    Route::prefix('inventaris')->name('invent.')->group(function () {
        Route::get('/', function () {
            return view('peminjam/inventaris');
        })->name('list');

        Route::get('detail/{id}', function () {
            return view('peminjam/detail-barang');
        })->name('detail');
    });
});

resources/views/peminjam/_sidebar.blade.php
<div class="col-lg-2 sidebar pr-0">
        <ul class="nav flex-column">
            <li class="menu-header">Dashboard</li>
            <li class="nav-item" id="beranda">
                <a href="{{ route('peminjam.index') }}" class="nav-link">
                    <i class="fa fa-tachometer"></i>
                    Dashboard
                </a>
            </li>
            <li class="menu-header">Modul</li>
            <li class="nav-item" id="inventaris">
                <a href="{{ route('peminjam.invent.list') }}" class="nav-link">
                    <i class="fa fa-dropbox"></i>
                    Inventaris
                </a>
            </li>
            <li class="nav-item" id="peminjaman">
                <a href="{{ route('peminjam.borrow.list') }}" class="nav-link">
                    <i class="fa fa-clipboard"></i>
                    Peminjaman
                </a>
            </li>
        </ul>
    </div

resources/views/peminjam/detail-barang.blade.php
@extends('template')

@section('content')

    <div class="row mt-5">
        <div class="col-md-7 col-sm-12">
            {{-- Inventory  image card --}}
            <div class="card">
                <div class="card-body">
                    <img src="{{ asset('img/epson-printer.jpeg') }}" alt="" style="width: 55vh" class="img-fluid img-center">
                </div>
            </div>
            {{-- End of inventory image card --}}
        </div>  
        <div class="col-md-5 col-sm-12">
            {{-- Inventory detail card --}}
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Printer Epson L330</h4>
                    <span class="text-blue mt-0 lead">B1-980</span>
                    <div class="row mt-3">
                        <div class="col">
                            <span>Jenis: Printer</span>
                        </div>
                        <div class="col">
                            <span>Stock: 5</span>
                        </div>
                        <div class="col">
                            <span>Kondisi: Baik</span>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-12">
                            <span>
                                Printer Epson L330 adalah sebuah printer handal keluaran epson yang dapat mencetak sebuah dokumen digital di kertas! seperti yang semua printer pada umunya lakukan! hebat bukan? INSCHOOL
                            </span>
                        </div>
                        <div class="col">
                            <a href="{{ route('peminjam.keranjang') }}" class="btn btn-md mt-5 bg-theme rounded-100 float-right">Pinjam</a>
                        </div>
                    </div>
                </div>
            </div>
            {{-- End of inventory detail card --}}
        </div>
    </div>
    
@endsection

resources/views/peminjam/detail-peminjaman.blade.php
@extends('template')

@section('content')

    <div class="row">
        <div class="col-md-8 col-sm-12">
            {{-- Borrow detail card --}}
            <div class="card mt-5">
                <div class="card-body">
                    <span class="rounded-100 bg-yellow p-3">Pending</span>

                    <p class="font-weight-bold mt-5">Barang yang dipinjam</p>
                    <table border="0" class="table mt-5">
                        <tr>
                            <td>1.</td>
                            <td>Laptop Thinkpad</td>
                            <td>3</td>
                        </tr>
                        <tr>
                            <td>2.</td>
                            <td>Proyektor Infocus</td>
                            <td>1</td>
                        </tr>
                        <tr>
                            <td>3.</td>
                            <td>Printer Epson L300</td>
                            <td>1</td>
                        </tr>
                    </table>
                </div>
            </div>
            {{-- End of borrow detail --}}
        </div>
        <div class="col-md-4 col-sm-12 mt-5">
            {{-- Borrower detail card --}}
            <div class="card">
                <div class="card-body">
                    <span class="font-weight-bold mb-4">Slim My Man</span>
                    <p class="mt-3">Tanggal pinjam <span class="float-right">21/02/2019</span></p>
                    <p class="mt-3">Total barang yang dipinjam <span class="float-right">05</span></p>
                </div>
            </div>
            {{-- End of borrower detail card --}}
        </div>
    </div>
    
@endsection

resources/views/peminjam/index.blade.php
@extends('template')

@section('content')

    <div class="row mt-5">
        <div class="col-lg-12">
            <div class="row">
                
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="ni ni-credit-card card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Jumlah Peminjaman</p>
                            <p class="text-semibold card-icon__number">21</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="ni ni-user-run card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Peminjaman Aktif</p>
                            <p class="text-semibold card-icon__number">21</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="card card-icon mb-4">
                        <div class="card-body text-center">
                            <i class="ni ni-folder-17 card-icon__icon"></i>
                            <p class="text-muted card-icon__text">Permintaan Peminjaman</p>
                            <p class="text-semibold card-icon__number">2</p>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">

                    <h3 class="text-semibold">Daftar Peminjaman Terakhir</h3>
                    <table id="myTable" class="table mt-3">
                        <thead class="bg-theme text-center">
                            <tr>
                                <th width="50">ID</th>
                                <th width="50">Jumlah Barang</th>
                                <th width="50">Tanggal Pinjam</th>
                                <th width="50" class="text-center">Status</th>
                                <th width="10" class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody class="text-center">
                            <tr>
                                <td class="align-middle">0567893</td>
                                <td class="align-middle">3</td>
                                <td class="align-middle">20/02/2019</td>
                                <td class="align-middle text-center">
                                        <span class="rounded-100 bg-yellow p-2">Pending</span>
                                </td>
                                <td class="align-middle text-center">
                                    <a href="{{ route('peminjam.borrow.detail', 45) }}" class="btn bg-theme rounded-100">Detail</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/peminjam/inventaris.blade.php
@extends('template')

@section('content')

    {{-- Inventory list card --}}
    <div class="row mt-5">
        <div class="col-sm-12 col-md-3 mt-3">
            <a href="{{ route('peminjam.invent.detail', 45) }}">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ asset('img/epson-printer.jpeg') }}" alt="" class="img-fluid">
                        <div class="mt-5">
                            <h5 class="card-title mb-0">Printer Epson L330</h5>
                            <small class="text-muted font-weight-bold">Jenis: Printer, Kondisi: Baik</small>
                        </div>
                        <p class="text-dark mt-3 mb-0">Stok: 5</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-12 col-md-3 mt-3">
            <a href="#">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ asset('img/epson-printer.jpeg') }}" alt="" class="img-fluid">
                        <div class="mt-5">
                            <h5 class="card-title mb-0">Printer Epson L331</h5>
                            <small class="text-muted font-weight-bold">Jenis: Printer, Kondisi: Baik</small>
                        </div>
                        <p class="text-dark mt-3 mb-0">Stok: 5</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-12 col-md-3 mt-3">
            <a href="#">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ asset('img/epson-printer.jpeg') }}" alt="" class="img-fluid">
                        <div class="mt-5">
                            <h5 class="card-title mb-0">Printer Epson L332</h5>
                            <small class="text-muted font-weight-bold">Jenis: Printer, Kondisi: Baik</small>
                        </div>
                        <p class="text-dark mt-3 mb-0">Stok: 5</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-12 col-md-3 mt-3">
            <a href="#">
                <div class="card">
                    <div class="card-body">
                        <img src="{{ asset('img/epson-printer.jpeg') }}" alt="" class="img-fluid">
                        <div class="mt-5">
                            <h5 class="card-title mb-0">Printer Epson L333</h5>
                            <small class="text-muted font-weight-bold">Jenis: Printer, Kondisi: Baik</small>
                        </div>
                        <p class="text-dark mt-3 mb-0">Stok: 5</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {{-- End of inventory list card --}}
    
@endsection

resources/views/peminjam/keranjang.blade.php
@extends('template')

@section('content')

    <div class="card mt-4">
        <div class="card-body">
            {{-- Cart table --}}
            <div class="table-responsive mt-4">
                <table class="table align-items-center">
                    <thead class="bg-theme  text-center">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nama Barang</th>
                            <th scope="col">Kode Barang</th>
                            <th scope="col">Kondisi</th>
                            <th scope="col" width="120">Qty</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <tr>
                            <td>1</td>
                            <td>Laptop Thinkpad</td>
                            <td>A1-254</td>
                            <td>Baik</td>
                            <td>
                                <input type="number" name="qty" id="qty" min="1" class="form-control mx-auto">    
                            </td> 
                            <td>
                                <a href="#" class="btn btn-danger rounded-100">Hapus</a>    
                            </td>   
                        </tr>    
                        <tr>
                            <td>2</td>
                            <td>Proyektor Infocus T678</td>
                            <td>C1-623</td>
                            <td>Baik</td>
                            <td>
                                <input type="number" name="qty" id="qty" min="1" class="form-control mx-auto">    
                            </td> 
                            <td>
                                <a href="#" class="btn btn-danger rounded-100">Hapus</a>    
                            </td>   
                        </tr>    
                        <tr>
                            <td>3</td>
                            <td>Printer Epson L330</td>
                            <td>B1-980</td>
                            <td>Baik</td>
                            <td>
                                <input type="number" name="qty" id="qty" min="1" class="form-control mx-auto">    
                            </td> 
                            <td>
                                <a href="#" class="btn btn-danger rounded-100">Hapus</a>    
                            </td>   
                        </tr>
                        <tr>
                            <td colspan="6" align="right">
                                <a href="" class="btn bg-theme rounded-100">Perbaharui</a>    
                            </td>    
                        </tr>    
                    </tbody>    
                </table>
            </div>
            {{-- End of cart table --}} 
        </div>
    </div>

    {{-- Cart overview --}}
    <div class="row mt-5">
        <div class="col-md-4 ml-auto">
            <div class="card">
                <div class="card-body">
                    <span class="font-weight-bold"> Slim My Man</span>
                    <p class="mt-3">Total barang yang dipinjam <span class="float-right">03</span></p>
                    <a href="#" class="btn bg-theme rounded-100 mt-2 float-right">Lanjutkan peminjaman</a>
                </div>
            </div>
        </div>
    </div>
    {{-- End of cart overview --}}

@endsection

resources/views/peminjam/list-peminjaman.blade.php
@extends('template')

@section('content')

    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-9">
                            <form class="form-inline">
                                <div class="form-group">
                                    <div class="input-group input-group-merge">
                                        <input class="form-control" placeholder="Search" type="text" id="search">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-search"></i></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group ml-3">
                                    <select id="sortBy" class="form-control">
                                        <option>Sort By</option>
                                        <option value="asc">Terbaru</option>
                                        <option value="desc">Terlama</option>
                                    </select>
                                </div>
                            </form>				
                        </div>
                    </div>
                            
                    <div class="row mt-2">
                        <table id="myTable" class="table mt-3">
                            <thead class="bg-theme text-center">
                                <tr>
                                    <th width="50">ID</th>
                                    <th width="50">Jumlah Barang</th>
                                    <th width="50">Tanggal Pinjam</th>
                                    <th width="50" class="text-center">Status</th>
                                    <th width="10" class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                <tr>
                                    <td class="align-middle">0567893</td>
                                    <td class="align-middle">3</td>
                                    <td class="align-middle">20/02/2019</td>
                                    <td class="align-middle text-center">
                                            <span class="rounded-100 bg-yellow p-2">Pending</span>
                                    </td>
                                    <td class="align-middle text-center">
                                        <a href="{{ route('peminjam.borrow.detail', 45) }}" class="btn bg-theme rounded-100">Detail</a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>    
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script>
        var table;
        $(function () {
            table = $('#myTable').dataTable({
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "bSort": true,
                "bFilter": true,
                "sDom": 'ltipr',
                "processing": true,
                "serverside": true,
                "ajax": {
                    url: '{{ url("/apipeminjam") }}',
                    type: "POST"
                },
                "columns": [
                    {"data": "id", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "qty", "sClass": "hide-sort align-middle", "bSortable": false},
                    {"data": "borrow_at", "sClass": "hide-sort align-middle", "bSortable": true},
                    {"data": "status", "sClass": "text-center align-middle", "bSortable": false},
                    {"data": "action", "sClass": "text-center align-middle", "bSortable": false}
                ],
                "aaSorting": [[2, "asc"]],
                "drawCallback": function (settings) {
                    $('.tip-right').tooltip({
                        container: 'body',
                        placement: 'right'
                    });
                }
            });

            $(".dataTables_length").remove();
            $(".mytable_filter").remove();

            $("#search").keyup(function(){
                table.fnFilter($(this).val());
            });

            $("#sortBy").change(function(){
                var val = $(this).val();
                table.fnSort([2, val]);
            });
        });
    </script>
@endsection